/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.LoginInicio;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Hamer
 */
public class User extends javax.swing.JFrame {
    private Color bgColor;
    private Color focusColor;
    /**
     * Creates new form Login
     */
    public User() {
        
        
        initComponents();
        buttonBook.setFocusable(true);
        bgColor = new Color(39, 60, 65); 
        focusColor = new Color(69, 87, 91);
        //userImage = new components.CircularLabel();
        userImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Userlog.png")));
        //this.setLocationRelativeTo(this);
        //SetImageLabel(userImage, "/Imagenes/userprofile.jpg");
        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        bookViewPanel1 = new guicomponents.BookViewPanel();
        menuPanel = new javax.swing.JPanel();
        buttonBook = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonLends = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttonGive = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        buttonReserve = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        userImage = new guicomponents.CircularLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));

        panel.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(bookViewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(652, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bookViewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPanel.setBackground(new java.awt.Color(39, 60, 65));

        buttonBook.setBackground(new java.awt.Color(39, 60, 65));
        buttonBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonBook.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                buttonBookFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                buttonBookFocusLost(evt);
            }
        });
        buttonBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonBookMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/libro.png"))); // NOI18N
        jLabel1.setText("LIBROS");
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });

        javax.swing.GroupLayout buttonBookLayout = new javax.swing.GroupLayout(buttonBook);
        buttonBook.setLayout(buttonBookLayout);
        buttonBookLayout.setHorizontalGroup(
            buttonBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        buttonBookLayout.setVerticalGroup(
            buttonBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonBookLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        buttonLends.setBackground(new java.awt.Color(39, 60, 65));
        buttonLends.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLends.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                buttonLendsFocusGained(evt);
            }
        });
        buttonLends.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonLendsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonLendsMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/documento.png"))); // NOI18N
        jLabel2.setText("PRESTAMOS");

        javax.swing.GroupLayout buttonLendsLayout = new javax.swing.GroupLayout(buttonLends);
        buttonLends.setLayout(buttonLendsLayout);
        buttonLendsLayout.setHorizontalGroup(
            buttonLendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonLendsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        buttonLendsLayout.setVerticalGroup(
            buttonLendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonLendsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        buttonGive.setBackground(new java.awt.Color(39, 60, 65));
        buttonGive.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonGive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonGiveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonGiveMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/regalo.png"))); // NOI18N
        jLabel3.setText("DONAR");

        javax.swing.GroupLayout buttonGiveLayout = new javax.swing.GroupLayout(buttonGive);
        buttonGive.setLayout(buttonGiveLayout);
        buttonGiveLayout.setHorizontalGroup(
            buttonGiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonGiveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        buttonGiveLayout.setVerticalGroup(
            buttonGiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonGiveLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        buttonReserve.setBackground(new java.awt.Color(39, 60, 65));
        buttonReserve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonReserve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonReserveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonReserveMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cascadia Mono", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reserva.png"))); // NOI18N
        jLabel4.setText("RESERVAS");

        javax.swing.GroupLayout buttonReserveLayout = new javax.swing.GroupLayout(buttonReserve);
        buttonReserve.setLayout(buttonReserveLayout);
        buttonReserveLayout.setHorizontalGroup(
            buttonReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonReserveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        buttonReserveLayout.setVerticalGroup(
            buttonReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonReserveLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        userImage.setBackground(new java.awt.Color(255, 255, 255));
        userImage.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        userImage.setForeground(new java.awt.Color(255, 255, 255));
        userImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Userlog.png"))); // NOI18N

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buttonLends, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buttonGive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buttonReserve, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(userImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(userImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonLends, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonGive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonReserve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLendsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buttonLendsFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLendsFocusGained

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel1FocusGained

    private void buttonBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBookMouseClicked
        // TODO add your handling code here:
        LoginInicio inicio = new LoginInicio();
        inicio.setVisible(true);
    }//GEN-LAST:event_buttonBookMouseClicked

    private void buttonBookFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buttonBookFocusGained
        
    
        
    }//GEN-LAST:event_buttonBookFocusGained

    private void buttonBookFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buttonBookFocusLost
       
        
    }//GEN-LAST:event_buttonBookFocusLost

    private void buttonBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBookMouseEntered
        // TODO add your handling code here:
        buttonBook.setBackground(focusColor);
    }//GEN-LAST:event_buttonBookMouseEntered

    private void buttonBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBookMouseExited
        // TODO add your handling code here:
        buttonBook.setBackground(bgColor);
    }//GEN-LAST:event_buttonBookMouseExited

    private void buttonLendsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLendsMouseEntered
        // TODO add your handling code here:
        buttonLends.setBackground(focusColor);
    }//GEN-LAST:event_buttonLendsMouseEntered

    private void buttonLendsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLendsMouseExited
        // TODO add your handling code here:
        buttonLends.setBackground(bgColor);
    }//GEN-LAST:event_buttonLendsMouseExited

    private void buttonGiveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGiveMouseEntered
        // TODO add your handling code here:
        buttonGive.setBackground(focusColor);
    }//GEN-LAST:event_buttonGiveMouseEntered

    private void buttonGiveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGiveMouseExited
        // TODO add your handling code here:
        buttonGive.setBackground(bgColor);
    }//GEN-LAST:event_buttonGiveMouseExited

    private void buttonReserveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonReserveMouseEntered
        // TODO add your handling code here:
        buttonReserve.setBackground(focusColor);
    }//GEN-LAST:event_buttonReserveMouseEntered

    private void buttonReserveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonReserveMouseExited
        // TODO add your handling code here:
        buttonReserve.setBackground(bgColor);
    }//GEN-LAST:event_buttonReserveMouseExited

    private void SetImageLabel(JLabel labelName, String root){
        //ImageIcon image = new ImageIcon(root);
        //Icon icon = new ImageIcon(
           //     image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT)
        //);
        labelName.setIcon(new ImageIcon(getClass().getResource("/imagenes/Userlog.png")));
        this.repaint();
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private guicomponents.BookViewPanel bookViewPanel1;
    private javax.swing.JPanel buttonBook;
    private javax.swing.JPanel buttonGive;
    private javax.swing.JPanel buttonLends;
    private javax.swing.JPanel buttonReserve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel panel;
    private guicomponents.CircularLabel userImage;
    // End of variables declaration//GEN-END:variables
}
